groups:
- name: HighCPU
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "高CPU使用率 (实例: {{ $labels.instance }})"
      description: "CPU使用率超过 80% (当前值: {{ $value }}%)"
