apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: 
          image: prom/node-exporter:v1.9.1
          ports:
            - containerPort: 9100
              name: 
          livenessProbe:
            httpGet:
              port: 9100
              path: /metrics
            initialDelaySeconds: 
            periodSeconds: 
            timeoutSeconds: 
            failureThreshold: 
          readinessProbe:
            httpGet:
              port: 9100
              path: /metrics
            initialDelaySeconds: 
            periodSeconds:
            successThreshold: 
            failureThreshold: 
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 
      name: 
  type: ClusterIP

